apiVersion: v2
name: ollama-router
description: A Helm chart for deploying the Ollama model-aware router.
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the appVersion.
version: 0.3.0
# This is the version number of the application being deployed. This version number should be
# identical to the Docker image tag of the application.
appVersion: "1.1.0"

dependencies:
  - name: common
    version: 5.0.0
    repository: https://bjw-s-labs.github.io/helm-charts